version: "3.9"

services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile

    volumes:
      - ./backend:/app

    ports:
      - 5000:5000

  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile

  #   volumes:
  #     - ./frontend:/app

  #   ports:
  #     - 4173:4173

  #   depends_on:
  #     - api
